About Me feature complete
ctrokid/CodeUTeam19 pull request #5
Opened 2019-02-28 03:09 UTC by srf6413

Everything should be all set. I did notice that before and after I sanitized user input , when I entered "<script>alert("Pay me a million dollars or I'll delete your files!");</script>" into the about me and posted, it did nothing instead of giving a javascript message. Let me know if there is something I missed but I'm pretty sure I followed the instructions exactly as they were...

2019-03-03 13:33 UTC, ctrokid requested changes
Nice, this looks good! I think not seeing the alert show up means that you are correctly sanitizing the user input.

Only question I have is if you were successfully able to deploy this to App Engine yet?

After that question and those two small fixes, I will approve.

2019-03-03 13:33 UTC, ctrokid commented on src/main/java/com/google/codeu/data/Datastore.java
> +
Nitpicky: could we remove this blank line?

2019-03-03 13:33 UTC, ctrokid commented on src/main/java/com/google/codeu/data/Datastore.java
> +
Same thing with this blank line?

2019-03-04 01:21 UTC, srf6413 commented
When I took the whitespace out, now travis is giving me an error:(

2019-03-04 03:14 UTC, ctrokid approved these changes
This LGTM. You'll just have to figure out the lint errors before it will let you submit 😛

2019-03-04 06:27 UTC, merged